name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: mkdir build && cp -R img build/img

      - name: Marp Build (webpage)
        uses: docker://marpteam/marp-cli:v2.5.0
        with:
          args: sensor_community_airrohr_workshop.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (sensor_community_airrohr_workshop.pdf)
        uses: docker://marpteam/marp-cli:v2.5.0
        with:
          args: sensor_community_airrohr_workshop.md --pdf --allow-local-files -o build/sensor_community_airrohr_workshop.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build (docs folder)
        uses: docker://marpteam/marp-cli:v2.5.0
        with:
          args: -I docs/ -o build/docs/
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
